version: "3.3"

services:
  bot:
    image: "${BOT_IMAGE_NAME}"
    container_name: "${BOT_CONTAINER_NAME}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
      - .:/usr/src/app/${BOT_NAME}
    command: python3 main.py
    restart: always
    env_file:
      - ".env"
  db:
    image: postgres
    container_name: "${BOT_CONTAINER_NAME}_DB"
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - "${DATABASE_PORT}:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  flyway:
    image: flyway/flyway:9.3.1
    command: -url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB} -user=${DATABASE_USER} -password=${DATABASE_PASSWORD} migrate
    volumes:
      - ./migrations:/flyway/sql
networks:
  bot:
    driver: bridge

volumes:
  cache:
  db: